---

- name: Manage local users and groups
  collections: [ 'debops.debops', 'debops.roles01',
                 'debops.roles02', 'debops.roles03' ]
  hosts: [ 'debops_all_hosts', 'debops_service_users' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: libuser
      tags: [ 'role::libuser', 'skip::libuser' ]

    - role: users
      tags: [ 'role::users', 'skip::users' ]

    - role: authorized_keys
      tags: [ 'role::authorized_keys', 'skip::authorized_keys' ]

    - role: sudo
      tags: [ 'role::sudo', 'skip::sudo' ]
      sudo__dependent_sudoers:
        - '{{ sshd__sudo__dependent_sudoers }}'

    - role: sshd
      tags: [ 'role::sshd', 'skip::sshd' ]
